// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJmGof8qMb3ooZDbdc4QhaEdLL3bvA1jo',
    appId: '1:699196602170:web:b51db263ddada11a1dc203',
    messagingSenderId: '699196602170',
    projectId: 'social-post-feed',
    authDomain: 'social-post-feed.firebaseapp.com',
    storageBucket: 'social-post-feed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuXapPa0epvgtchuj3X0E5MjuDhYZjiCM',
    appId: '1:699196602170:android:6ec1f29918585cf31dc203',
    messagingSenderId: '699196602170',
    projectId: 'social-post-feed',
    storageBucket: 'social-post-feed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV7udaUsvViebtB1Vh_j2OnQ7NbnKUxeU',
    appId: '1:699196602170:ios:1be47c3fef7373d41dc203',
    messagingSenderId: '699196602170',
    projectId: 'social-post-feed',
    storageBucket: 'social-post-feed.firebasestorage.app',
    iosBundleId: 'com.example.socialPostFeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV7udaUsvViebtB1Vh_j2OnQ7NbnKUxeU',
    appId: '1:699196602170:ios:1be47c3fef7373d41dc203',
    messagingSenderId: '699196602170',
    projectId: 'social-post-feed',
    storageBucket: 'social-post-feed.firebasestorage.app',
    iosBundleId: 'com.example.socialPostFeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJmGof8qMb3ooZDbdc4QhaEdLL3bvA1jo',
    appId: '1:699196602170:web:e7ee003d974e5a541dc203',
    messagingSenderId: '699196602170',
    projectId: 'social-post-feed',
    authDomain: 'social-post-feed.firebaseapp.com',
    storageBucket: 'social-post-feed.firebasestorage.app',
  );
}
